targets:
  $default:
    builders:
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routes/app_routers.dart 

 