name: skeleton
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  ansicolor: ^2.0.2
  auto_route: ^7.8.0
  auto_route_generator: ^7.2.0
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  hidable: ^1.0.5
  hovering: ^1.0.4
  http: ^1.1.0
  liquid_pull_to_refresh: ^3.0.1
  logging: ^1.2.0
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/2.png"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/cert.pem
