name: Build Flutter Web App and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  Build Web APP:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --web-renderer canvaskit

      - name: Archive build directory
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/web

  Deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SECRET_KEY }}

      - name: Checkout Server Repository
        uses: actions/checkout@v4
        with:
          repository: SangheliosBlack/TramitaTuVisaOnlineServer
          ref: main
          ssh-key: ${{ secrets.SECRET_KEY }}
          path: server

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: /tmp/my_build

      - name: Copy build to server repository
        run: cp -r /tmp/my_build/. server/public

      - name: Commit and Push to Server Repository
        run: |
          cd server
          git config --global user.name "SangheliosBlack"
          git config --global user.email "julio.villagrana.sanghelios2@gmail.com"
          git add -A
          git commit -m "Update build"
          git push origin main
