name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.5.0

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web --web-renderer canvaskit

    - name: Archive build directory
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/web

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Server Repository
      uses: actions/checkout@v2.5.0
      with:
        repository: SangheliosBlack/TramitaTuVisaOnlineServer
        path: public
        ref: main

    - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: /tmp/my_build

    - name: Copy build to server repository
      run: cp -r /tmp/my_build/. public/

    - name: Commit and Push to Server Repository
      run: |
        cd public
        git config --global user.name "SangheliosBlack"
        git config --global user.email "julio.villagrana.sanghelios2@gmail.com"
        git add -A
        git commit -m "Update build"
        git push origin main
