name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.5.0

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web --web-renderer canvaskit

    - name: Archive build directory
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/web

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Server Repository
      uses: actions/checkout@v2.5.0
      with:
        repository: SangheliosBlack/TramitaTuVisaOnlineServer
        path: public
        ref: main
        ssh-key: ${{ secrets.SECRET_KEY }} 

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: /tmp/my_build

    - name: Copy build to server repository
      run: cp -r /tmp/my_build/. public/
    
    - name: Commit and Push to Server Repository
      run: |
        cd public
        git config --global user.name "SangheliosBlack"
        git config --global user.email "julio.villagrana.sanghelios2@gmail.com"
    
        # Configuración de la clave SSH (si estás usando una clave SSH)
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.SECRET_KEY }}"
    
        # Configuración de git para usar el agente SSH
        git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa'
    
        # Realizar el commit
        git add -A
        git commit -m "Update build"
    
        # Realizar el push utilizando el agente SSH
        git push origin main
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    

